package com.mycompany.weatherapp.entityhistory;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Column;
import lombok.Data;

import java.time.LocalDateTime;

@Entity
@Data
public class WeatherHistory {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String city;
    private String weather;
    private String temperature;

    @Column(name = "timestamp", columnDefinition = "TIMESTAMP")  // Optional if needed for custom database column types
    private LocalDateTime timestamp;


    // Getters and Setters (Generated by Lombok)
}
